HL7/smart-app-launch

- .gitignore
- spec/index.md
ballot#208 #201 minor text change
> Ballot#206

- .gitignore
- spec/index.md
ballot#208 #201 minor text change
> Ballot#208

- spec/index.md
"Theme: "Signed Tokens"
Ballot#120, Ballot#51
#124, #55
> Signed tokens

- spec/dist/bootstrap-fhir.css
- spec/index.md
Ballot#183 , #180 add whitespace before headers
( I have no idea why when I update the fork,  all the Merging is showing  up on the PRs,)
> Ballot#183

- spec/scopes-and-launch-context/index.md
Theme: "Scope Design"
Ballot#184, Ballot#182, Ballot#168, Ballot#145, Ballot#144, Ballot#143, Ballot#130, Ballot#69, Ballot#8 
#181, #179, #165, #142, #140, #141, #132, #74, #13
> Scope design

- spec/conformance/index.md
See discussion at https://chat.fhir.org/#narrow/stream/14-smart/topic/CapabilityStatement.20URIs
> Note a recommendation for absolute OAuth endpoint URIs

- .gitignore
- fsh/ig-data/input/pages/scopes-v2-wip.md
Updated text around interactions.
Added clarification around scope interaction orders.
> Interaction updates for review

- fsh/ig-data/input/pages/scopes-v2-wip.md
Took an initial cut at some guidance to provide the development community when they are considering the use of the more in-depth scopes that SMART v2 offers.
> Consent guidance - Initial release for review by the team.

- fsh/ig-data/input/pages/conformance.md
Complete the transition of discovery to .well-known
> Finalize deprecation of CapabilityStatement extensions

- FHIR-smart.xml
- input/ignoreWarnings.txt
- sushi-config.yaml
> prettify TOC

- FHIR-smart.xml
- input/ignoreWarnings.txt
- package-list.json
- sushi-config.yaml
> update ballot version to 1.1.0 and add 'ballot' to title

- input/pages/index.md
- package-list.json
updated index with note to balloters updating changes and package list for history file.
> add note to balloters

- ig.ini
- input/ignoreWarnings.txt
- sushi-config.yaml
to clarify: update the package code
> update canonical to hl7.fhir.uv.smart-app-launch

- input/pages/index.md
- input/pages/scopes-and-launch-context.md
This PR includes all the changes applied from ballot comment resolutions that affect the Scopes and Launch Context pages.
These changes were originally applied to a different branch (which had additional changes beyond the resolution work) so this branch was created and the commits were cherry picked onto this branch using:
```sh
git cherry-pick d167fcf5...cad692df
```
> Scopes and launch IG updates

- sushi-config.yaml
> update title and version to proper version 2.0.0

- sushi-config.yaml
> align table of contents

- input/pages/best-practices.md
I have a question about this text:
"Client architectures where data pass through or are stored in a secure backend server (e.g., many confidential clients) can offer more secure {refresh token :: client} binding,...
what is  {refresh token :: client} binding ???
> best practices page edits

- input/pages/scopes-and-launch-context.md
confused this  and think is "granted these scopes by a  system" and  not 'user' is meant.  if its user  meant then User needs to be defined in this context. ( see my edits in diff )
> even more scopes and launch edits

- input/images-source/overview-backend-services.plantuml
- input/pages/backend-services.md
> backend services pages

- input/images-source/overview-app-launch.plantuml
"Access token request" should be going to "EHR with Authorization Server" and not "FHIR Server"
> Typo: App issues request to EHR authorization server for access token
